package com.myapp.struts;
// Generated 28/03/2016 10:50:46 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmple;
     private Formapagos formapagos;
     private Tiempopagos tiempopagos;
     private Usuario usuario;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String fechaNaci;
     private String direccion;
     private String telefono;
     private String fechaContratacion;
     private BigDecimal sueldo;
     private Set nominases = new HashSet(0);

    public Empleados() {
    }

    public Empleados(Formapagos formapagos, Tiempopagos tiempopagos, Usuario usuario, String nombre, String apaterno, String amaterno, String fechaNaci, String direccion, String telefono, String fechaContratacion, BigDecimal sueldo, Set nominases) {
       this.formapagos = formapagos;
       this.tiempopagos = tiempopagos;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.fechaNaci = fechaNaci;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fechaContratacion = fechaContratacion;
       this.sueldo = sueldo;
       this.nominases = nominases;
    }
   
    public Integer getIdEmple() {
        return this.idEmple;
    }
    
    public void setIdEmple(Integer idEmple) {
        this.idEmple = idEmple;
    }
    public Formapagos getFormapagos() {
        return this.formapagos;
    }
    
    public void setFormapagos(Formapagos formapagos) {
        this.formapagos = formapagos;
    }
    public Tiempopagos getTiempopagos() {
        return this.tiempopagos;
    }
    
    public void setTiempopagos(Tiempopagos tiempopagos) {
        this.tiempopagos = tiempopagos;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getFechaNaci() {
        return this.fechaNaci;
    }
    
    public void setFechaNaci(String fechaNaci) {
        this.fechaNaci = fechaNaci;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(String fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public BigDecimal getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(BigDecimal sueldo) {
        this.sueldo = sueldo;
    }
    public Set getNominases() {
        return this.nominases;
    }
    
    public void setNominases(Set nominases) {
        this.nominases = nominases;
    }




}


