package com.myapp.struts;
// Generated 28/03/2016 10:50:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formapagos generated by hbm2java
 */
public class Formapagos  implements java.io.Serializable {


     private Integer idFormaPago;
     private String formaPago;
     private Set empleadoses = new HashSet(0);

    public Formapagos() {
    }

    public Formapagos(String formaPago, Set empleadoses) {
       this.formaPago = formaPago;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(Integer idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


