package com.myapp.struts;
// Generated 6/04/2016 07:23:24 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Nominas generated by hbm2java
 */
public class Nominas  implements java.io.Serializable {


     private Integer idNomina;
     private Empleados empleados;
     private BigDecimal sueldoBruto;
     private BigDecimal isr;
     private BigDecimal ssm;
     private BigDecimal infonavit;
     private BigDecimal subTotal;
     private BigDecimal sueldoNeto;

    public Nominas() {
    }

	
    public Nominas(Empleados empleados) {
        this.empleados = empleados;
    }
    public Nominas(Empleados empleados, BigDecimal sueldoBruto, BigDecimal isr, BigDecimal ssm, BigDecimal infonavit, BigDecimal subTotal, BigDecimal sueldoNeto) {
       this.empleados = empleados;
       this.sueldoBruto = sueldoBruto;
       this.isr = isr;
       this.ssm = ssm;
       this.infonavit = infonavit;
       this.subTotal = subTotal;
       this.sueldoNeto = sueldoNeto;
    }
   
    public Integer getIdNomina() {
        return this.idNomina;
    }
    
    public void setIdNomina(Integer idNomina) {
        this.idNomina = idNomina;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public BigDecimal getSueldoBruto() {
        return this.sueldoBruto;
    }
    
    public void setSueldoBruto(BigDecimal sueldoBruto) {
        this.sueldoBruto = sueldoBruto;
    }
    public BigDecimal getIsr() {
        return this.isr;
    }
    
    public void setIsr(BigDecimal isr) {
        this.isr = isr;
    }
    public BigDecimal getSsm() {
        return this.ssm;
    }
    
    public void setSsm(BigDecimal ssm) {
        this.ssm = ssm;
    }
    public BigDecimal getInfonavit() {
        return this.infonavit;
    }
    
    public void setInfonavit(BigDecimal infonavit) {
        this.infonavit = infonavit;
    }
    public BigDecimal getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }
    public BigDecimal getSueldoNeto() {
        return this.sueldoNeto;
    }
    
    public void setSueldoNeto(BigDecimal sueldoNeto) {
        this.sueldoNeto = sueldoNeto;
    }




}


