package com.myapp.struts;
// Generated 23/03/2016 07:34:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiempopagos generated by hbm2java
 */
public class Tiempopagos  implements java.io.Serializable {


     private Integer idTiempoPago;
     private String tipoPago;
     private Set empleadoses = new HashSet(0);

    public Tiempopagos() {
    }

    public Tiempopagos(String tipoPago, Set empleadoses) {
       this.tipoPago = tipoPago;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdTiempoPago() {
        return this.idTiempoPago;
    }
    
    public void setIdTiempoPago(Integer idTiempoPago) {
        this.idTiempoPago = idTiempoPago;
    }
    public String getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


